import { db } from '../db/db';
import * as schema from '../db/schema';

// await db.delete(schema.tarots);

await db.insert(schema.tarots).values([
  // {
  //   name: 'The Fool',
  //   type: 'major arcana',
  //   rank: '0',
  //   suit: 'hearts',
  //   element: 'earth',
  //   planet: 'uranus',
  //   meaning: ['love', 'rage'],
  // },
  {
    name: 'The Fool',
    type: 'major arcana',
    rank: '0',
    element: 'Air',
    planet: 'Uranus',
    sign: ['Aries'],
    meaning: ['Spontaneity, new beginnings, free spirit'],
  },
  {
    name: 'The Magician',
    type: 'major arcana',
    rank: '1',
    element: 'Mercury',
    planet: 'Mercury',
    sign: ['Aries'],
    meaning: ['Skill, action, manifestation'],
  },
  {
    name: 'The High Priestess',
    type: 'major arcana',
    rank: '2',
    element: 'Water',
    planet: 'Moon',
    sign: ['Pisces, Cancer'],
    meaning: ['Intuition, mystery, inner wisdom'],
  },
  {
    name: 'The Empress',
    type: 'major arcana',
    rank: '3',
    element: 'Venus',
    planet: 'Venus',
    sign: ['Taurus'],
    meaning: ['Fertility, abundance, nurturing'],
  },
  {
    name: 'The Emperor',
    type: 'major arcana',
    rank: '4',
    element: 'Aries',
    planet: 'Aries',
    sign: ['Aries'],
    meaning: ['Authority, structure, discipline'],
  },
  {
    name: 'The Hierophant',
    type: 'major arcana',
    rank: '5',
    element: 'Taurus',
    planet: 'Venus',
    sign: ['Taurus'],
    meaning: ['Tradition, conformity, spiritual guidance'],
  },
  {
    name: 'The Lovers',
    type: 'major arcana',
    rank: '6',
    element: 'Air',
    planet: 'Gemini',
    sign: ['Gemini'],
    meaning: ['Relationships, choices, harmony'],
  },
  {
    name: 'The Chariot',
    type: 'major arcana',
    rank: '7',
    element: 'Cancer',
    planet: 'Moon',
    sign: ['Cancer'],
    meaning: ['Willpower, victory, control'],
  },
  {
    name: 'Strength',
    type: 'major arcana',
    rank: '8',
    element: 'Leo',
    planet: 'Sun',
    sign: ['Leo'],
    meaning: ['Courage, self-control, inner strength'],
  },
  {
    name: 'The Hermit',
    type: 'major arcana',
    rank: '9',
    element: 'Virgo',
    planet: 'Mercury',
    sign: ['Virgo'],
    meaning: ['Introspection, wisdom, solitude'],
  },
  {
    name: 'Wheel of Fortune',
    type: 'major arcana',
    rank: '10',
    element: 'Jupiter',
    planet: 'Jupiter',
    sign: ['Sagittarius, Pisces'],
    meaning: ['Luck, cycles, fate'],
  },
  {
    name: 'Justice',
    type: 'major arcana',
    rank: '11',
    element: 'Libra',
    planet: 'Saturn',
    sign: ['Libra'],
    meaning: ['Balance, fairness, accountability'],
  },
  {
    name: 'The Hanged Man',
    type: 'major arcana',
    rank: '12',
    element: 'Water',
    planet: 'Neptune',
    sign: ['Pisces'],
    meaning: ['Sacrifice, surrender, new perspective'],
  },
  {
    name: 'Death',
    type: 'major arcana',
    rank: '13',
    element: 'Scorpio',
    planet: 'Pluto',
    sign: ['Scorpio'],
    meaning: ['Transformation, endings, change'],
  },
  {
    name: 'Temperance',
    type: 'major arcana',
    rank: '14',
    element: 'Sagittarius',
    planet: 'Jupiter',
    sign: ['Sagittarius'],
    meaning: ['Balance, moderation, patience'],
  },
  {
    name: 'The Devil',
    type: 'major arcana',
    rank: '15',
    element: 'Capricorn',
    planet: 'Saturn',
    sign: ['Capricorn'],
    meaning: ['Temptation, materialism, addiction'],
  },
  {
    name: 'The Tower',
    type: 'major arcana',
    rank: '16',
    element: 'Mars',
    planet: 'Mars',
    sign: ['Aries'],
    meaning: ['Upheaval, sudden change, destruction'],
  },
  {
    name: 'The Star',
    type: 'major arcana',
    rank: '17',
    element: 'Aquarius',
    planet: 'Uranus',
    sign: ['Aquarius'],
    meaning: ['Hope, inspiration, renewal'],
  },
  {
    name: 'The Moon',
    type: 'major arcana',
    rank: '18',
    element: 'Pisces',
    planet: 'Moon',
    sign: ['Pisces'],
    meaning: ['Illusion, intuition, subconscious'],
  },
  {
    name: 'The Sun',
    type: 'major arcana',
    rank: '19',
    element: 'Leo',
    planet: 'Sun',
    sign: ['Leo'],
    meaning: ['Vitality, joy, success'],
  },
  {
    name: 'Judgement',
    type: 'major arcana',
    rank: '20',
    element: 'Pluto',
    planet: 'Pluto',
    sign: ['Scorpio'],
    meaning: ['Rebirth, awakening, inner calling'],
  },
  {
    name: 'The World',
    type: 'major arcana',
    rank: '21',
    element: 'Saturn',
    planet: 'Saturn',
    sign: ['Capricorn'],
    meaning: ['Completion, wholeness, success'],
  },
  {
    name: 'Ace of Wands',
    type: 'minor arcana',
    rank: '1',
    suit: 'wands',
    element: 'Fire',
    planet: 'Mars',
    sign: ['Aries'],
    meaning: ['Inspiration, new beginnings, creativity'],
  },
  {
    name: 'Two of Wands',
    type: 'minor arcana',
    rank: '2',
    suit: 'wands',
    element: 'Fire',
    planet: 'Mars',
    sign: ['Aries'],
    meaning: ['Planning, foresight, power'],
  },
  {
    name: 'Three of Wands',
    type: 'minor arcana',
    rank: '3',
    suit: 'wands',
    element: 'Fire',
    planet: 'Sun',
    sign: ['Aries'],
    meaning: ['Expansion, progress, success'],
  },
  {
    name: 'Four of Wands',
    type: 'minor arcana',
    rank: '4',
    suit: 'wands',
    element: 'Fire',
    planet: 'Venus',
    sign: ['Aries'],
    meaning: ['Celebration, community, stability'],
  },
  {
    name: 'Five of Wands',
    type: 'minor arcana',
    rank: '5',
    suit: 'wands',
    element: 'Fire',
    planet: 'Mars',
    sign: ['Leo'],
    meaning: ['Conflict, competition, struggle'],
  },
  {
    name: 'Six of Wands',
    type: 'minor arcana',
    rank: '6',
    suit: 'wands',
    element: 'Fire',
    planet: 'Sun',
    sign: ['Leo'],
    meaning: ['Victory, recognition, success'],
  },
  {
    name: 'Seven of Wands',
    type: 'minor arcana',
    rank: '7',
    suit: 'wands',
    element: 'Fire',
    planet: 'Mars',
    sign: ['Leo'],
    meaning: ['Courage, defense, perseverance'],
  },
  {
    name: 'Eight of Wands',
    type: 'minor arcana',
    rank: '8',
    suit: 'wands',
    element: 'Fire',
    planet: 'Mercury',
    sign: ['Sagittarius'],
    meaning: ['Swiftness, action, communication'],
  },
  {
    name: 'Nine of Wands',
    type: 'minor arcana',
    rank: '9',
    suit: 'wands',
    element: 'Fire',
    planet: 'Moon',
    sign: ['Sagittarius'],
    meaning: ['Resilience, perseverance, defense'],
  },
  {
    name: 'Ten of Wands',
    type: 'minor arcana',
    rank: '10',
    suit: 'wands',
    element: 'Fire',
    planet: 'Saturn',
    sign: ['Sagittarius'],
    meaning: ['Burden, overwork, responsibility'],
  },
  {
    name: 'Page of Wands',
    type: 'court cards',
    rank: 'Page',
    suit: 'wands',
    element: 'Fire',
    planet: 'Mercury',
    sign: ['Sagittarius', 'Aries', 'Leo'],
    meaning: ['Enthusiasm, new ideas, exploration'],
  },
  {
    name: 'Knight of Wands',
    type: 'court cards',
    rank: 'Knight',
    suit: 'wands',
    element: 'Fire',
    planet: 'Mars',
    sign: ['Aries', 'Leo', 'Sagittarius'],
    meaning: ['Passion, impulsiveness, adventure'],
  },
  {
    name: 'Queen of Wands',
    type: 'court cards',
    rank: 'Queen',
    suit: 'wands',
    element: 'Fire',
    planet: 'Sun',
    sign: ['Aries', 'Leo', 'Sagittarius'],
    meaning: ['Confidence, creativity, independence'],
  },
  {
    name: 'King of Wands',
    type: 'court cards',
    rank: 'King',
    suit: 'wands',
    element: 'Fire',
    planet: 'Mars',
    sign: ['Aries', 'Leo', 'Sagittarius'],
    meaning: ['Leadership, vision, entrepreneurship'],
  },
  {
    name: 'Ace of Cups',
    type: 'minor arcana',
    rank: '1',
    suit: 'cups',
    element: 'Water',
    planet: 'Moon',
    sign: ['Cancer'],
    meaning: ['Emotional fulfillment, love, intuition'],
  },
  {
    name: 'Two of Cups',
    type: 'minor arcana',
    rank: '2',
    suit: 'cups',
    element: 'Water',
    planet: 'Venus',
    sign: ['Cancer'],
    meaning: ['Partnership, connection, attraction'],
  },
  {
    name: 'Three of Cups',
    type: 'minor arcana',
    rank: '3',
    suit: 'cups',
    element: 'Water',
    planet: 'Jupiter',
    sign: ['Cancer'],
    meaning: ['Celebration, community, joy'],
  },
  {
    name: 'Four of Cups',
    type: 'minor arcana',
    rank: '4',
    suit: 'cups',
    element: 'Water',
    planet: 'Moon',
    sign: ['Cancer'],
    meaning: ['Apathy, boredom, introspection'],
  },
  {
    name: 'Five of Cups',
    type: 'minor arcana',
    rank: '5',
    suit: 'cups',
    element: 'Water',
    planet: 'Saturn',
    sign: ['Scorpio'],
    meaning: ['Loss, regret, disappointment'],
  },
  {
    name: 'Six of Cups',
    type: 'minor arcana',
    rank: '6',
    suit: 'cups',
    element: 'Water',
    planet: 'Sun',
    sign: ['Scorpio'],
    meaning: ['Nostalgia, innocence, childhood'],
  },
  {
    name: 'Seven of Cups',
    type: 'minor arcana',
    rank: '7',
    suit: 'cups',
    element: 'Water',
    planet: 'Venus',
    sign: ['Scorpio'],
    meaning: ['Illusion, fantasy, choices'],
  },
  {
    name: 'Eight of Cups',
    type: 'minor arcana',
    rank: '8',
    suit: 'cups',
    element: 'Water',
    planet: 'Saturn',
    sign: ['Pisces'],
    meaning: ['Abandonment, withdrawal, disillusionment'],
  },
  {
    name: 'Nine of Cups',
    type: 'minor arcana',
    rank: '9',
    suit: 'cups',
    element: 'Water',
    planet: 'Jupiter',
    sign: ['Pisces'],
    meaning: ['Satisfaction, contentment, wish fulfillment'],
  },
  {
    name: 'Ten of Cups',
    type: 'minor arcana',
    rank: '10',
    suit: 'cups',
    element: 'Water',
    planet: 'Moon',
    sign: ['Pisces'],
    meaning: ['Harmony, emotional fulfillment, family'],
  },
  {
    name: 'Page of Cups',
    type: 'court cards',
    rank: 'Page',
    suit: 'cups',
    element: 'Water',
    planet: 'Mercury',
    sign: ['Pisces', 'Cancer', 'Scorpio'],
    meaning: ['Sensitivity, imagination, new emotions'],
  },
  {
    name: 'Knight of Cups',
    type: 'court cards',
    rank: 'Knight',
    suit: 'cups',
    element: 'Water',
    planet: 'Jupiter',
    sign: ['Pisces', 'Cancer', 'Scorpio'],
    meaning: ['Romanticism, creativity, daydreaming'],
  },
  {
    name: 'Queen of Cups',
    type: 'court cards',
    rank: 'Queen',
    suit: 'cups',
    element: 'Water',
    planet: 'Moon',
    sign: ['Pisces', 'Cancer', 'Scorpio'],
    meaning: ['Empathy, intuition, emotional intelligence'],
  },
  {
    name: 'King of Cups',
    type: 'court cards',
    rank: 'King',
    suit: 'cups',
    element: 'Water',
    planet: 'Jupiter',
    sign: ['Pisces', 'Cancer', 'Scorpio'],
    meaning: ['Emotional maturity, compassion, diplomacy'],
  },
  {
    name: 'Ace of Swords',
    type: 'minor arcana',
    rank: '1',
    suit: 'swords',
    element: 'Air',
    planet: 'Mars',
    sign: ['Aries'],
    meaning: ['Clarity, truth, new ideas'],
  },
  {
    name: 'Two of Swords',
    type: 'minor arcana',
    rank: '2',
    suit: 'swords',
    element: 'Air',
    planet: 'Moon',
    sign: ['Libra'],
    meaning: ['Indecision, stalemate, avoidance'],
  },
  {
    name: 'Three of Swords',
    type: 'minor arcana',
    rank: '3',
    suit: 'swords',
    element: 'Air',
    planet: 'Saturn',
    sign: ['Libra'],
    meaning: ['Heartbreak, sorrow, betrayal'],
  },
  {
    name: 'Four of Swords',
    type: 'minor arcana',
    rank: '4',
    suit: 'swords',
    element: 'Air',
    planet: 'Jupiter',
    sign: ['Libra'],
    meaning: ['Rest, retreat, contemplation'],
  },
  {
    name: 'Five of Swords',
    type: 'minor arcana',
    rank: '5',
    suit: 'swords',
    element: 'Air',
    planet: 'Venus',
    sign: ['Aquarius'],
    meaning: ['Conflict, defeat, resentment'],
  },
  {
    name: 'Six of Swords',
    type: 'minor arcana',
    rank: '6',
    suit: 'swords',
    element: 'Air',
    planet: 'Mercury',
    sign: ['Gemini', 'Virgo'],
    meaning: ['Transition, movement, journey, leaving difficulties behind'],
  },
  {
    name: 'Seven of Swords',
    type: 'minor arcana',
    rank: '7',
    suit: 'swords',
    element: 'Air',
    planet: 'Moon',
    sign: ['Aquarius'],
    meaning: ['Cunning, deception, strategy, escaping'],
  },
  {
    name: 'Eight of Swords',
    type: 'minor arcana',
    rank: '8',
    suit: 'swords',
    element: 'Air',
    planet: 'Saturn',
    sign: ['Gemini', 'Virgo'],
    meaning: ['Restriction, entrapment, helplessness, self-imposed limitations'],
  },
  {
    name: 'Nine of Swords',
    type: 'minor arcana',
    rank: '9',
    suit: 'swords',
    element: 'Air',
    planet: 'Mars',
    sign: ['Gemini', 'Virgo'],
    meaning: ['Anxiety, nightmares, depression, suffering'],
  },
  {
    name: 'Ten of Swords',
    type: 'minor arcana',
    rank: '10',
    suit: 'swords',
    element: 'Air',
    planet: 'Sun',
    sign: ['Gemini', 'Virgo'],
    meaning: ['Defeat, betrayal, ending, rock bottom'],
  },
  {
    name: 'Page of Swords',
    type: 'court cards',
    rank: 'Page',
    suit: 'swords',
    element: 'Air',
    planet: 'Mercury',
    sign: ['Gemini', 'Libra', 'Aquarius'],
    meaning: ['Curiosity, intellect, communication, vigilance'],
  },
  {
    name: 'Knight of Swords',
    type: 'court cards',
    rank: 'Knight',
    suit: 'swords',
    element: 'Air',
    planet: 'Mars',
    sign: ['Aries', 'Gemini', 'Libra'],
    meaning: ['Action, aggression, speed, impulsiveness'],
  },
  {
    name: 'Queen of Swords',
    type: 'court cards',
    rank: 'Queen',
    suit: 'swords',
    element: 'Air',
    planet: 'Jupiter',
    sign: ['Libra', 'Aquarius', 'Gemini'],
    meaning: ['Objectivity, independence, intellect, discernment'],
  },
  {
    name: 'King of Swords',
    type: 'court cards',
    rank: 'King',
    suit: 'swords',
    element: 'Air',
    planet: 'Saturn',
    sign: ['Libra', 'Aquarius', 'Gemini'],
    meaning: ['Authority, logic, justice, decisiveness'],
  },
  {
    name: 'Ace of Pentacles',
    type: 'minor arcana',
    rank: '1',
    suit: 'pentacles',
    element: 'Earth',
    planet: 'Saturn',
    sign: ['Taurus', 'Virgo', 'Capricorn'],
    meaning: ['Manifestation, prosperity, security, grounding'],
  },
  {
    name: 'Two of Pentacles',
    type: 'minor arcana',
    rank: '2',
    suit: 'pentacles',
    element: 'Earth',
    planet: 'Jupiter',
    sign: ['Taurus', 'Virgo'],
    meaning: ['Balance, duality, adaptability, juggling'],
  },
  {
    name: 'Three of Pentacles',
    type: 'minor arcana',
    rank: '3',
    suit: 'pentacles',
    element: 'Earth',
    planet: 'Sun',
    sign: ['Taurus', 'Virgo'],
    meaning: ['Skill, craftsmanship, collaboration, teamwork'],
  },
  {
    name: 'Four of Pentacles',
    type: 'minor arcana',
    rank: '4',
    suit: 'pentacles',
    element: 'Earth',
    planet: 'Saturn',
    sign: ['Taurus', 'Virgo'],
    meaning: ['Greed, miserliness, possessiveness, stinginess'],
  },
  {
    name: 'Five of Pentacles',
    type: 'minor arcana',
    rank: '5',
    suit: 'pentacles',
    element: 'Earth',
    planet: 'Mercury',
    sign: ['Taurus', 'Virgo'],
    meaning: ['Hardship, poverty, loss, isolation'],
  },
  {
    name: 'Six of Pentacles',
    type: 'minor arcana',
    rank: '6',
    suit: 'pentacles',
    element: 'Earth',
    planet: 'Jupiter',
    sign: ['Taurus', 'Virgo'],
    meaning: ['Generosity, charity, sharing, philanthropy'],
  },
  {
    name: 'Seven of Pentacles',
    type: 'minor arcana',
    rank: '7',
    suit: 'pentacles',
    element: 'Earth',
    planet: 'Saturn',
    sign: ['Taurus', 'Virgo'],
    meaning: ['Patience, perseverance, investment, planning'],
  },
  {
    name: 'Eight of Pentacles',
    type: 'minor arcana',
    rank: '8',
    suit: 'pentacles',
    element: 'Earth',
    planet: 'Mercury',
    sign: ['Virgo'],
    meaning: ['Apprenticeship, skill, diligence, work'],
  },
  {
    name: 'Nine of Pentacles',
    type: 'minor arcana',
    rank: '9',
    suit: 'pentacles',
    element: 'Earth',
    planet: 'Venus',
    sign: ['Virgo'],
    meaning: ['Luxury, self-sufficiency, independence'],
  },
  {
    name: 'Ten of Pentacles',
    type: 'minor arcana',
    rank: '10',
    suit: 'pentacles',
    element: 'Earth',
    planet: 'Saturn',
    sign: ['Virgo', 'Taurus'],
    meaning: ['Wealth, family, legacy, tradition'],
  },
  {
    name: 'Page of Pentacles',
    type: 'court cards',
    rank: 'Page',
    suit: 'pentacles',
    element: 'Earth',
    planet: 'Mercury',
    sign: ['Taurus', 'Virgo', 'Capricorn'],
    meaning: ['Practicality, resourcefulness, new opportunities'],
  },
  {
    name: 'Knight of Pentacles',
    type: 'court cards',
    rank: 'Knight',
    suit: 'pentacles',
    element: 'Earth',
    planet: 'Saturn',
    sign: ['Taurus', 'Virgo', 'Capricorn'],
    meaning: ['Patience, persistence, reliability, responsibility'],
  },
  {
    name: 'Queen of Pentacles',
    type: 'court cards',
    rank: 'Queen',
    suit: 'pentacles',
    element: 'Earth',
    planet: 'Venus',
    sign: ['Taurus', 'Virgo', 'Capricorn'],
    meaning: ['Nurturing, abundance, sensuality, practicality'],
  },
  {
    name: 'King of Pentacles',
    type: 'court cards',
    rank: 'King',
    suit: 'pentacles',
    element: 'Earth',
    planet: 'Jupiter',
    sign: ['Taurus', 'Virgo', 'Capricorn'],
    meaning: ['Prosperity, authority, business acumen, materialism'],
  },
]);

console.log(`Seeding complete.`);
//FIXME: connection doesn't close
